config/routes.rb
Rails.application.routes.draw do


  root to: 'sessions#log_in'
  get "main", to: "main#index", as: "main"

  post 'sign_in', to: 'sessions#sign_in'
  delete 'signout', to: 'sessions#destroy'

  get 'clients/search', to: "clients#search", as: 'clients_search'
  resources :clients

  get 'search/new', to: "searches#new", as: 'new_search'
  post 'search/create', to: "searches#create", as: 'adv_search'
  
  get 'search/invoices', to: "searches#invoices_search", as: 'adv_invoice_search'
  resources :invoices  , except: [:destroy] do
    resources :invoice_products , only: [:index,:new,:edit,:create,:update, :destroy]
  end
  resources :charged_persons , only: [:create,:destroy]
  resources :payments
  resources :products , except: [:show,:destroy] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  include InvoicesTestable
  belongs_to :client , counter_cache: :invoices_count
  has_many :invoice_products
  has_many :products , through: :invoice_products
  has_many :payments

  validates :number, presence: {message:'رقم الفاتورة مطلوب'}, numericality: {only_integer:true, message: 'رقم الفاتورة يجب ان يكون رقم صحيح'}
  validates :value , presence:{message: 'قيمة الفاتورة مطلوبة'}, numericality: {message: 'قيمة الفاتورة يجب ان تكون رقم'}
  validates :client_id , presence: {message: "العميل مطلوب"}
  validates :date , presence: {message: 'تاريخ الفاتورة مطلوب'}

  after_save :calculate_client_total_sales

  scope :total_value , lambda { sum(:value)}
  scope :total_paid, lambda { sum(:paid)}
  scope :filter_by_remaining_balance, lambda {where(arel_table[:value].gt(arel_table[:paid]))}
  scope :select_client_name, lambda {joins(:client).select(Client.arel_table[:name])}
  scope :filter_by_value_range , lambda {|min , max| where(value: min..max) }
  scope :filter_by_number , lambda { |number| where(number: number)}
  scope :filter_by_client_name , lambda { |name| 
    joins(:client)
    .where(Client.aq(:name , :matches , "%#{name}%"))  
  }
  scope :filter_by_client_area , lambda { |area| 
    joins(:client)
    .where(Client.aq(:area, :matches , "%#{area}%"))  
  }
  scope :filter_by_in_time_range , lambda { |start_date , end_date|  where(date: start_date..end_date) }
  scope :totals , lambda {
    data= select(aq(:value , :sum).as("total_value"))
    .select(aq(:paid, :sum).as("total_payments"))
    .unscope(:order)
    .unscope(:group)
    .to_a
    .first

    return {
      value: data["total_value"],
      payments: data["total_payments"],
      remaining_balance: (data["total_value"] || 0.0) - (data["total_payments"] || 0.0)
    }
  }

  #---------------------------------------------
  def payments_remaining
    value - payments.total
  end

  def calculate_client_total_sales
    client.update({
      sales: client.invoices.sum(:value) ,
      remaining_balance: (client.invoices.sum(:value) - client.invoices.joins(:payments).sum(:amount)),
      paid: client.invoices.joins(:payments).sum(:amount)
      })
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :authenticate_user
  before_action :set_invoice , only: [:show, :edit,:update]

  has_scope :filter_by_client_name , as: :client_name
  has_scope :filter_by_client_area , as: :client_area
  has_scope :filter_by_number , as: :number
  has_scope :filter_by_remaining_balance , as: :remaining_balance, type: :boolean
  has_scope :filter_by_value_range, as: :value_between , using: %i[min_value max_value] , type: :hash
  has_scope :filter_by_in_time_range , as: :invoices_between , using: %i[start_date end_date], type: :hash
  has_scope :not_full_paid_since 

  include ApplicationHelper
  
  def index
    begin
      @invoices = apply_scopes(Invoice).all
      @totals= @invoices.totals
      @invoices = @invoices.select_all_columns.select_client_name.order(date: :desc)
    rescue Exception => e 
      redirect_to new_search_path,alert: "حدث خطأ أثناء البحث"
    end
  end

  def new
    @invoice= Invoice.new(client_id: params[:client_id] || nil)
  end

  def create
    @invoice = Invoice.new(invoices_params)
    if @invoice.save()
      redirect_to @invoice , notice: 'تم اضافة الفاتورة بنجاح'
    else
      render :new
    end

  end

  def show
    @products= @invoice.invoice_products
  end

  def edit
  end

  def update
    if @invoice.update(invoices_params)
      redirect_to @invoice.client, notice: 'تم تحديث الفاتورة بنجاح'
    else
      render :edit
    end
  end

  private
  def invoices_params
    params.require(:invoice).permit(:client_id,:number,:value,:payment_method,:date,:paid)
  end

  def set_invoice
    @invoice = Invoice.find_by(id: params[:id])
    redirect_to clients_path , alert: 'رقم الفاتورة خاطئ' unless @invoice.present?
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper

  def invoice_value_matches_products_value?(invoice)
    order_products = invoice.invoice_products
    products_value = 0
    order_products.each do |order_product|
      products_value += (order_product.product.price * order_product.quantity)
    end

    invoice.value == products_value
  end

  
  def calculate_total_value(invoice_products)
    total = 0
    invoice_products.each do |invoice_product|
      total += (invoice_product.quantity * invoice_product.product.price)
    end
    return total
  end
end

app/views/invoices/edit.html.erb
<h3>فاتورة شراء</h3>

 <div class='form-control'>

    <%= form_for @invoice , url: invoice_path do  |form| %>
      <% if @invoice.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <% @invoice.errors.full_messages.each do |msg| %>
            <div><%= '* ' + msg %></div>
          <% end %>
        </div>
      <% end %>

      <div class='m-3'>
        <%= form.label "العميل", class: 'form-label' %>
        <%= form.collection_select :client_id, Client.all , :id , :name ,class: 'form-control' %>
      </div> 

      <div class='m-3'>
        <%= form.label "رقم الفاتورة", class: 'form-label' %>
        <%= form.text_field :number, class: 'form-control' %>
      </div>

      <div class='m-3'>
        <%= form.label "قيمة الفاتورة", class: 'form-label' %>
        <%= form.text_field :value, class: 'form-control' %>
      </div>


      <div class='m-3'>
        <%= form.label "تاريخ الفاتورة", class: 'form-label' %>
        <%= form.date_field :date  %>
      </div>

      <div class='m-3 mb-3'> 

        <%= form.submit 'حفظ', class: 'btn btn-success' %>
        <%= link_to "عودة", client_path(@invoice.client) , class: 'btn btn-primary' %>
      </div>


    <%end%>

  </div>

app/views/invoices/index.html.erb
<h1>
  الفواتير
</h1>
<hr>
<div class='table-responsive mt-2 mb-3'>
  <table class='table table-success table-hover '>
    <thead class='table-dark'>
            <tr>
              <th scope="col">#</th>
              <th scope="col">العميل</th>
              <th scope="col">رقم الفاتورة</th>
              <th scope="col">تاريخ الفاتورة</th>
              <th scope="col">قيمة الفاتورة</th>
              <th scope="col">المبالغ المدفوعة</th>
              <th scope="col">المبلغ المتبقي</th>
              <th scope='col'></th>
            </tr>
          </thead>
          <tbody>
            <%@invoices.each_with_index do |invoice , idx|%>
              <tr>
                <th scope='row'><%= idx+1 %></th>
                <td><%= invoice["name"]%> </td>
                <td><%= invoice[:number]%> </td>
                <td><%= invoice[:date]%></td>
                <td><%= invoice[:value]%></td>
                <td><%= invoice[:paid] || 0.0%> </td>
                <td><%= invoice[:value] - (invoice[:paid] || 0.0) %></td>
                <td>
                  <%= link_to "عرض", invoice_path(id: invoice[:id]), class: 'btn btn-outline-primary btn-sm' %>
                  <%= link_to "تحديث", edit_invoice_path(id: invoice[:id]), class: 'btn btn-outline-success btn-sm' %>
                  <%= link_to "سداد", new_payment_path(invoice_id: invoice[:id]), class: 'btn btn-outline-danger btn-sm' %>
                </td>
              </tr>
            <%end%>
          </tbody>
          <tfoot class='table-dark'>
            <tr>
              <th>#</th>
              <td></td>
              <td></td>
              <td></td>
              <td><%= @totals[:value] %></td>
              <td><%= @totals[:payments] %></td>
              <td><%= @totals[:remaining_balance]%></td>
              <td></td>
            </tr>
          </tfoot>
  </table>

  <%= link_to "بحث" , new_search_path ,class: 'btn btn-sm btn-success' %>
  <%= link_to "الرئيسية" , main_path ,class: 'btn btn-sm btn-primary' %>
</div>

app/views/invoices/new.html.erb
<h3>فاتورة شراء</h3>

 <div class='form-control'>

    <%= form_for @invoice , url: invoices_path do  |form| %>
      <% if @invoice.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <% @invoice.errors.full_messages.each do |msg| %>
            <div><%= '* ' + msg %></div>
          <% end %>
        </div>
      <% end %>

      <div class='m-3'>
        <%= form.label "العميل", class: 'form-label' %>
        <%= form.collection_select :client_id, Client.all, :id , :name ,class: 'form-control' %>
      </div> 

      <div class='m-3'>
        <%= form.label "رقم الفاتورة", class: 'form-label' %>
        <%= form.text_field :number, class: 'form-control' %>
      </div>

      <div class='m-3'>
        <%= form.label "قيمة الفاتورة", class: 'form-label' %>
        <%= form.text_field :value, class: 'form-control' %>
      </div>


      <div class='m-3'>
        <%= form.label "تاريخ الفاتورة", class: 'form-label' %>
        <%= form.date_field :date  %>
      </div>

      <div class='m-3 mb-3'> 

        <%= form.submit 'حفظ', class: 'btn btn-success' %>
        <%= link_to "عودة", clients_path , class: 'btn btn-primary' %>
      </div>


    <%end%>

  </div>

app/views/invoices/show.html.erb
<h1><%= @invoice.client.name %></h1>
<hr>
<h6>رقم الفاتورة : <%= @invoice.number %></h6>
<h6>اجمالي الفاتورة : <%= @invoice.value %></h6>
<h6>تاريخ الفاتورة : <%= @invoice.date %></h6>
<h6>اجمالي المدفوعات : <%= @invoice.paid %></h6>
<h6>المبلغ المتبقي في الفاتورة : <%= @invoice.value - @invoice.paid %></h6>
<div class="mt-3">
  <%= link_to "اضافة المنتجات" , new_invoice_invoice_product_path(invoice_id: @invoice.id) , class: 'btn btn-sm btn-danger' unless invoice_value_matches_products_value?(@invoice) %>
  <div class='table-responsive mt-2'>
    <table class='table table-success table-hover'>
      <thead class='table-dark'>
        <tr>
          <th scope="col">#</th>
          <th scope="col">المنتجات</th>
          <th scope="col">الكمية</th>
          <th scope="col">سعر الوحدة</th>
          <th scope="col">المجموع الكلي</th>
          <th scope="col">الضريبة المضافة</th>
          <th scope="col">الاجمالي</th>
          <th scope='col'></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each_with_index do |invoice_product, idx|%>
          <tr>
            <th scope='row'><%= idx+1 %></th>
            <td><%= invoice_product.product.name%> </td>
            <td><%= invoice_product.quantity%></td>
            <td><%= detach_vat(invoice_product.product.price)%></td>
            <td><%= detach_vat(invoice_product.product.price * invoice_product.quantity) %></td>
            <td><%= extract_vat(invoice_product.product.price * invoice_product.quantity) %></td>
            <td><%= (invoice_product.product.price * invoice_product.quantity).to_f.round(2) %></td>
            <td>
              <%= link_to "تعديل", edit_invoice_invoice_product_path(@invoice,invoice_product), class: 'btn btn-outline-primary btn-sm' %>
              <%= link_to "حذف", invoice_invoice_product_path(@invoice,invoice_product),method: :delete, class: 'btn btn-outline-danger btn-sm' %>
            </td>
          </tr>
        <%end%>    
      </tbody>
      <tfoot class='table-dark'>
      <tr>
        <th>#</th>
        <td></td>
        <td><%= @products.sum(:quantity) %></td>
        <td></td>
        <td><%= detach_vat(calculate_total_value(@products)) %></td>
        <td><%= extract_vat(calculate_total_value(@products)) %></td>
        <td><%= calculate_total_value(@products) %></td>
        <td></td>
      </tr>
    </tfoot>
    </table>
  </div>
</div>
<div class='mt-3'>
  <div class='mt-2 px-2'>
    <%= link_to "اضافة سداد" , new_payment_path(invoice_id: @invoice.id) , class: 'btn btn-sm btn-success' %>
    <% if @invoice.payments.count > 0 %>
      <div class='table-responsive mt-2'>
        <table class='table table-success table-hover'>
          <thead class='table-dark'>
            <tr>
              <th scope="col">#</th>
              <th scope="col">تاريخ السداد</th>
              <th scope="col">مبلغ السداد</th>
              <th scope="col">طريقة السداد</th>
              <th scope='col'></th>
            </tr>
          </thead>
          <tbody>
            <%@invoice.payments.each do |payment|%>
              <tr>
                <th scope='row'><%= payment.id %></th>
                <td><%= payment.date%> </td>
                <td><%= payment.amount%></td>
                <td><%= payment.payment_method%></td>
                <td>
                  <%= link_to "تعديل", edit_payment_path(id: payment.id), class: 'btn btn-outline-primary btn-sm' %>
                  <%= link_to "حذف", payment_path(id: payment.id),method: :delete, class: 'btn btn-outline-danger btn-sm' %>
                </td>
              </tr>
            <%end%>
            
          </tbody>
        </table>
      </div>
    <% end %>
    <hr>
    <%= link_to 'عودة',@invoice.client , class: 'btn btn-primary btn-sm' %>
  </div>
</div>