config/routes.rb
Rails.application.routes.draw do


  root to: 'sessions#log_in'
  get "main", to: "main#index", as: "main"

  post 'sign_in', to: 'sessions#sign_in'
  delete 'signout', to: 'sessions#destroy'

  get 'clients/search', to: "clients#search", as: 'clients_search'
  resources :clients

  get 'search/new', to: "searches#new", as: 'new_search'
  post 'search/create', to: "searches#create", as: 'adv_search'
  
  get 'search/invoices', to: "searches#invoices_search", as: 'adv_invoice_search'
  resources :invoices  , except: [:destroy] do
    resources :invoice_products , only: [:index,:new,:edit,:create,:update, :destroy]
  end
  resources :charged_persons , only: [:create,:destroy]
  resources :payments
  resources :products , except: [:show,:destroy] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"> 
    <span style='color: black'><%= flash[:notice] %></span>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <span style='color: black'><%= flash[:alert] %></span>
  </div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <%= link_to "كرمه" , main_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <%= link_to "العملاء", clients_path , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "المنتجات", products_path , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "الفواتير", invoices_path , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "اضافة عميل", new_client_path , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "فاتورة جديدة", new_invoice_path , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "بحث", new_search_path , class: 'nav-link' %>
        </li>
      </ul>
      <form class="d-flex">
        <%= link_to 'تسجيل الخروج', signout_path(Current.user),method: :delete, class:"btn btn-sm btn-outline-secondary" %>
      </form>
    </div>
  </div>
</nav>