config/routes.rb
Rails.application.routes.draw do


  root to: 'sessions#log_in'
  get "main", to: "main#index", as: "main"

  post 'sign_in', to: 'sessions#sign_in'
  delete 'signout', to: 'sessions#destroy'

  get 'clients/search', to: "clients#search", as: 'clients_search'
  resources :clients

  get 'search/new', to: "searches#new", as: 'new_search'
  post 'search/create', to: "searches#create", as: 'adv_search'
  
  get 'search/invoices', to: "searches#invoices_search", as: 'adv_invoice_search'
  resources :invoices  , except: [:destroy] do
    resources :invoice_products , only: [:index,:new,:edit,:create,:update, :destroy]
  end
  resources :charged_persons , only: [:create,:destroy]
  resources :payments
  resources :products , except: [:show,:destroy] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/client.rb
class Client < ApplicationRecord
  include Testable
  has_many :invoices
  has_many :charged_persons
  has_many :payments , through: :invoices

  validates :name, presence: {message: 'الاسم مطلوب'}
  validates :area, presence: {message: 'المنطقة مطلوبة'}

  scope :total_sales, -> {joins(:invoices).sum(Invoice.arel_table[:value])}
  scope :total_payments, -> {joins(invoices: :payments).sum(Payment.arel_table[:amount])}
  scope :total_invoices_count, -> {joins(:invoices).count(Invoice.arel_table[:client_id])}
  scope :filter_by_name, -> (name) {where(aq(:name,:matches,"%#{name}%")) }
  scope :filter_by_area, -> (area) {where(aq(:area,:matches,"%#{area}%"))}
  scope :filter_by_remaining_balance, -> {where(aq(:remaining_balance,:gt,"0"))}
  scope :where_ids_in, -> (ids)  { where(id: ids)}
  scope :totals, lambda {
    data =  select(aq(:sales,:sum).as("total_sales"))
      .select(aq(:paid,:sum).as("total_payments"))
      .select(aq(:remaining_balance,:sum).as("total_remaining_balance"))
      .select(aq(:invoices_count,:sum).as("total_invoices_count"))
      .select(aq(:id,:count).as("total_clients_count"))
      .unscope(:order)
      .unscope(:group)
      .to_a
      .first

    return {
      sales: data["total_sales"],
      payments: data["total_payments"],
      remaining_balance: data["total_remaining_balance"],
      invoices_count: data["total_invoices_count"],
      clients: data["total_clients_count"]
    }
  }

  scope :filter_by_invoices_in_time_range , lambda { |start_date,end_date| 
    filtered_invoices = Invoice.arel_table
      .project(Invoice.arel_table[:client_id])
      .where(Invoice.arel_table[:date].between(start_date..end_date))
      .group(Invoice.arel_table[:client_id])
      .as("filtered_invoices")

    joins(
      arel_table
      .join(filtered_invoices)
      .on(arel_table[:id].eq(filtered_invoices[:client_id]))
      .join_sources
    )
  }

  #--------------------------------

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :authenticate_user
  before_action :set_client, only: [:show,:edit,:update]

  has_scope :filter_by_name , as: :name
  has_scope :filter_by_area , as: :area
  has_scope :filter_by_remaining_balance , as: :with_payments_remaining , type: :boolean
  has_scope :filter_by_invoices_in_time_range, as: :invoices_between, using: %i[start_date end_date ] , type: :hash
  has_scope :where_ids_in, as: :ids, type: :array


  def index
    @clients = Client.order(:id)
    @totals = @clients.totals
  end

  def create
    @client = Client.new(clients_params)
    
    if @client.save()
      redirect_to @client, notice: "تم اضافة العميل بنجاح"
    else
      render :new 
    end
  end

  def search 
    begin
      @clients= apply_scopes(Client).all.order(:id)
      @totals = @clients.totals
    rescue Exception => e
      redirect_to new_search_path, alert: "حدث خطأ أثناء البحث"
    end
  end
  
  
  def new
    @client = Client.new
  end

  def show
  end

  def edit
  end

  def update
    if @client.update(clients_params)
      redirect_to @client , notice: 'تم تحديث العميل بنجاح'
    else
      render :edit
    end
  end

  private
  def clients_params
    params.require(:client).permit(:name,:area)
  end

  def set_client
      @client = Client.find_by(id: params[:id])
      redirect_to clients_path, alert: 'رقم العميل غير صحيح' unless @client.present?
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<div class='mt-3'>
  <h3>تحديث بيانات عميل : </h3>
  <div class='form-control'>

    <%= form_for @client , url: client_path(@client), method: 'PATCH' do  |form| %>
      <% if @client.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <% @client.errors.full_messages.each do |msg| %>
            <div><%= '* ' + msg %></div>
          <% end %>
        </div>
      <% end %> 

      <div class='m-3'>
        <%= form.label "الاسم", class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class='m-3'>
        <%= form.label "المنطقة", class: 'form-label' %>
        <%= form.text_field :area, class: 'form-control' %>
      </div>

      <div class='m-3 mb-3'>
        <%= form.submit 'حفظ', class: 'btn btn-success' %>
        <%= link_to "عودة", client_path(@client), class: 'btn btn-primary' %>
      </div>


    <%end%>

  </div>
</div>

app/views/clients/index.html.erb
<h1>
  قائمة العملاء
</h1>
<hr>
<div>
  <h6>اجمالي عدد العملاء: <%= @totals[:clients] %></h6>
  <h6>اجمالي المبيعات: <%= @totals[:sales] %></h6>
  <h6>اجمالي المدفوعات: <%= @totals[:payments] %></h6>

  <p class='px-4'>
    - اجمالي النقدي: <%= Payment.total_cash %><br>
    - اجمالي التحويل البنكي: <%= Payment.total_transfer %>
  </p>
  <h6>اجمالي المتبقي: <%= @totals[:sales] - @totals[:payments] %></h6>
</div>
<hr>
  <%
=begin%>
 <div>
    <%= render partial: 'clients/partials/search'%>
  </div>
<hr> 
<%
=end%>
<div class='table-responsive mt-2'>
  <table class='table table-success table-hover '>
    <thead class='table-dark'>
      <tr>
        <th scope="col">#</th>
        <th scope="col">الاسم</th>
        <th scope="col">المنطقة</th>
        <th scope="col">عدد الفواتير</th>
        <th scope="col">قيمة الفواتير</th>
        <th scope="col">المبالغ المسددة</th>
        <th scope="col">المبلغ المتبقي</th>
        <th scope='col'></th>
      </tr>
    </thead>
    <tbody>
      <%@clients.each_with_index do |client, idx|%>
        <tr>
          <th scope='row'><%= idx+1 %></th>
          <td><%= client.name%> </td>
          <td><%= client.area%></td>
          <td><%= client.invoices_count || 0 %></td>
          <td><%=client.sales || 0.0 %></td>
          <td><%=client.paid || 0.0 %></td>
          <td><%= client.remaining_balance || 0.0%></td>
          <td><%= link_to "عرض", client_path(id:client.id), class: 'btn btn-outline-success btn-sm' %></td>
        </tr>
      <%end%>
    <tfoot class='table-dark'>
      <tr>
        <th>#</th>
        <td></td>
        <td></td>
        <td><%= @totals[:invoices_count] %></td>
        <td><%= @totals[:sales] %></td>
        <td><%= @totals[:payments] %></td>
        <td><%= @totals[:remaining_balance] %></td>
        <td></td>
        <td></td>
      </tr>
    </tfoot>
    </tbody>
  </table>

  
</div>

app/views/clients/new.html.erb
<div class='mt-3'>
  <h3>عميل جديد : </h3>
  <div class='form-control'>

    <%= form_for @client , url: clients_path do  |form| %>
      <% if @client.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <% @client.errors.full_messages.each do |msg| %>
            <div><%= '* ' + msg %></div>
          <% end %>
        </div>
      <% end %> 

      <div class='m-3'>
        <%= form.label "الاسم", class: 'form-label' %>
        <%= form.text_field :name , auto_complete:false, class: 'form-control' %>
      </div>


      <div class='m-3'>
        <%= form.label "المنطقة", class: 'form-label' %>
        <%= form.text_field :area, class: 'form-control' %>
      </div>

      <div class='m-3 mb-3'>
        <%= form.submit 'حفظ', class: 'btn btn-success' %>
        <%= link_to "عودة", clients_path , class: 'btn btn-primary' %>
      </div>


    <%end%>

  </div>
</div>

app/views/clients/search.html.erb
<h1>
  بحث العملاء
</h1>
<hr>
<div class='table-responsive mt-2'>
  <table class='table table-success table-hover '>
    <thead class='table-dark'>
      <tr>
        <th scope="col">#</th>
        <th scope="col">الاسم</th>
        <th scope="col">المنطقة</th>
        <th scope="col">عدد الفواتير</th>
        <th scope="col">قيمة الفواتير</th>
        <th scope="col">قيمة المدفوعات</th>
        <th scope="col">المبلغ المتبقي</th>
        <th scope='col'></th>
      </tr>
    </thead>
    <tbody>
      <%@clients.each_with_index do |client , idx|%>
        <tr>
          <th scope='row'><%= idx+1 %></th>
          <td><%= client[:name]%> </td>
          <td><%= client[:area]%></td>
          <td><%= client[:invoices_count] || 0%></td>
          <td><%=client[:sales] || 0.0 %></td>
          <td><%=client[:paid] || 0.0 %></td>
          <td><%= client[:remaining_balance] || 0.0%></td>
          <td><%= link_to "عرض", client_path(id:client[:id]), class: 'btn btn-outline-success btn-sm' %></td>
        </tr>
      <%end%>
    </tbody>
    <tfoot class='table-dark'>
      <tr>
        <th>#</th>
        <td></td>
        <td></td>
        <td><%= @totals[:invoices_count]%></td>
        <td><%= @totals[:sales]%></td>
        <td><%= @totals[:payments]%></td>
        <td><%= @totals[:remaining_balance]%></td>
        <td></td>
      </tr>
    </tfoot>
  </table>

  <%= link_to "بحث جديد" , new_search_path ,class: 'btn btn-sm btn-success' %>
  <%= link_to "عودة" , clients_path ,class: 'btn btn-sm btn-primary' %>
</div>

app/views/clients/show.html.erb
<h1><%= @client.name %></h1>

<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <button class="nav-link active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">
      الفواتير
    </button>
    <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">
      تفاصيل العميل
    </button>

  </div>
</nav>


<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
    <div class='mt-2 px-2'>
      <%= link_to "اضافة فاتورة" , new_invoice_path(client_id: @client.id) , class: 'btn btn-sm btn-success' %>
      <div class='table-responsive mt-2'>
        <table class='table table-success table-hover'>
          <thead class='table-dark'>
            <tr>
              <th scope="col">#</th>
              <th scope="col">رقم الفاتورة</th>
              <th scope="col">تاريخ الفاتورة</th>
              <th scope="col">قيمة الفاتورة</th>
              <th scope="col">المبالغ المدفوعة</th>
              <th scope="col">المبلغ المتبقي</th>
              <th scope='col'></th>
            </tr>
          </thead>
          <tbody>
            <%@client.invoices.each_with_index do |invoice, idx|%>
              <tr>
                <th scope='row'><%= idx+1 %></th>
                <td><%= invoice.number%> </td>
                <td><%= invoice.date%></td>
                <td><%= invoice.value%></td>
                <td><%= invoice.paid%> </td>
                <td><%= (invoice.value - invoice.paid) %></td>
                <td>
                  <%= link_to "عرض", invoice_path(invoice), class: 'btn btn-outline-primary btn-sm' %>
                  <%= link_to "تحديث", edit_invoice_path(invoice), class: 'btn btn-outline-success btn-sm' %>
                  <%= link_to "سداد", new_payment_path(invoice_id: invoice.id), class: 'btn btn-outline-danger btn-sm' %>
                </td>
              </tr>
            <%end%>
          
          </tbody>
          <tfoot class='table-dark'>
              <tr>
                <th>#</th>
                <td></td>
                <td></td>
                <td><%= @client.sales%></td>
                <td><%= @client.paid%></td>
                <td><%= @client.remaining_balance%></td>
                <td></td>
              </tr>
            </tfoot>
        </table>
      </div>
    </div>
  </div>


  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
    <div class='mt-2 px-4 border-success'>
      المنطقة: <%= @client.area %>
    </div>
    <hr>
    <div class='mt-2 px-4 border-success'>
      عدد الفواتير: <%= @client.invoices_count %>
    </div>
    <hr>
    <div class='mt-2 px-4 border-success'>
      اجمالي قيمة الفواتير: <%= @client.sales %>
    </div>
    <hr>
    <div class='mt-2 px-4 border-success'>
      اجمالي المبالغ المسددة:  <%= @client.paid %>
    </div>
    <hr>
    <div class='mt-2 px-4 border-success'>
      <h6>      اجمالي المبالغ المتبقية:  <%= @client.remaining_balance %></h6>
    </div>
    <hr>
    <div class='mt-2 px-4 border-success'>
      الاشخاص المسؤولين: 
      <div>
        <%= render partial: 'clients/partials/newChargedPerson' %>
      </div>
      
      <% if @client.charged_persons.count > 0 %>
        <div class='table-responsive mt-2'>
          <table class='table table-success table-hover'>
            <thead class='table-dark'>
              <tr>
                <th scope="col">#</th>
                <th scope="col">الاسم</th>
                <th scope="col">رقم الهاتف</th>
                <th scope="col">صفته</th>
                <th scope='col'></th>
              </tr>
            </thead>
            <tbody>
              <%@client.charged_persons.each do |charged_person|%>
                <tr>
                  <th scope='row'><%= charged_person.id %></th>
                  <td><%= charged_person.name%> </td>
                  <td><%= charged_person.phone%></td>
                  <td><%= charged_person.title%></td>
                  <td>
                    <%= link_to "تحديث", client_path(@client), class: 'btn btn-outline-primary btn-sm' %>
                    <%= link_to "حذف", charged_person_path(charged_person),method: :delete, class: 'btn btn-outline-danger btn-sm' %>
                  </td>
                </tr>
              <%end%>
            
            </tbody>
          </table>
        </div>
      <% end %>
    </div>

    <div class='my-2 px-4 border-success'>
      <%= link_to "تحديث بيانات العميل" , edit_client_path(id: @client.id) , class: 'btn btn-primary btn-sm' %>
    </div> 
  </div>

  <hr>

  <%= link_to 'عودة', clients_path, class: 'btn btn-primary btn-sm' %>
  
</div>