config/routes.rb
Rails.application.routes.draw do


  root to: 'sessions#log_in'
  get "main", to: "main#index", as: "main"

  post 'sign_in', to: 'sessions#sign_in'
  delete 'signout', to: 'sessions#destroy'

  get 'clients/search', to: "clients#search", as: 'clients_search'
  resources :clients

  get 'search/new', to: "searches#new", as: 'new_search'
  post 'search/create', to: "searches#create", as: 'adv_search'
  
  get 'search/invoices', to: "searches#invoices_search", as: 'adv_invoice_search'
  resources :invoices  , except: [:destroy] do
    resources :invoice_products , only: [:index,:new,:edit,:create,:update, :destroy]
  end
  resources :charged_persons , only: [:create,:destroy]
  resources :payments
  resources :products , except: [:show,:destroy] 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :invoice
  delegate :client , to: :invoice
  # rename to total
  scope :total, -> {sum(:amount)}
  scope :total_cash, -> {where(payment_method: 'cash').sum(:amount)}
  scope :total_transfer, -> {where(payment_method: 'transfer').sum(:amount) }

  after_save :reset_calculation
  after_destroy :reset_calculation

  validates :amount, presence: {message: 'المبلغ المدفوع مطلوب'} , numericality: {message: "المبلغ يجب ان يكون رقم"}
  validates :payment_method , presence: {message: 'طريقة السداد مطلوبة'} , inclusion: { in: ['cash', 'transfer'] , message: 'طريقة السداد اما نقدا او تحويل بنكي'}
  validates :date , presence: {message: 'تاريخ السداد مطلوب'}

  def reset_calculation
    invoice.update(paid: invoice.payments.total)
  end



#------


  


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user
  before_action :set_invoice, only: [:new,:show]
  before_action :set_payment, only: [:destroy, :edit, :update]

  def new 
    @payment= Payment.new(invoice_id: @invoice.id)
  end

  def show 
  end

  def destroy
    invoice = @payment.invoice
    if @payment.destroy 
      flash[:notice]= 'تم حذف السداد بنجاح'
    else
      falsh[:alert]= 'خطا اثناء حذف سداد'
    end

    redirect_to invoice
  end

  def create 
    @payment = Payment.new(payments_params)
    if @payment.save
      redirect_to @payment.invoice, notice: 'تم اضافة السداد بنجاح'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @payment.update(payments_params)
      redirect_to @payment.invoice, notice: 'تم تحديث معلومات السداد بنجاح'
    else
      render :edit
    end
  end

  private

  def payments_params
    params.require(:payment).permit(:invoice_id,:amount,:payment_method,:date)
  end

  def set_invoice 
    @invoice = Invoice.find_by(id: params[:invoice_id])
    redirect_to clients_path , alert: 'الفاتورة المطلوبة غير صحيحة' unless @invoice.present?
  end

  def set_payment
    @payment= Payment.find_by(id: params[:id])
    redirect_to clients_path , alert: 'رقم السداد غير صحيح' unless @payment.present?
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/edit.html.erb
<div class='mt-3'>
  <h3>تعديل سداد فاتورة : </h3>

  <div class='m-2'>
    <p><%= @payment.invoice.client.name %></p>
    <p>رقم الفاتورة : <%= @payment.invoice.number %></p>
    <p>قيمة الفاتورة : <%= @payment.invoice.value %></p>
    <p>المبلغ المتبقي : <%= @payment.invoice.payments_remaining %></p>
  </div>
  <div class='form-control'>

    <%= form_for @payment , url: payment_path, mthod: 'PATCH' do  |form| %>
      <% if @payment.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <% @payment.errors.full_messages.each do |msg| %>
            <div><%= '* ' + msg %></div>
          <% end %>
        </div>
      <% end %> 

      <%= form.hidden_field :invoice_id , value: @payment.invoice_id %>

      <div class='m-3'>
        <%= form.label "المبلغ", class: 'form-label' %>
        <%= form.text_field :amount, class: 'form-control' %>
      </div>

      <div class='m-3'>
        <%= form.label "طريقة السداد", class: 'form-label' %>
        <%= form.select :payment_method, [['نقدا','cash'], ['تحويل بنكي', 'transfer']], class: 'form-control' %>
      </div>

      <div class='m-3'>
        <%= form.label "تاريخ السداد", class: 'form-label' %>
        <%= form.date_field :date %>
      </div>

      <div class='m-3 mb-3'>
        <%= form.submit 'حفظ', class: 'btn btn-success' %>
        <%= link_to "عودة", invoice_path(@payment.invoice) , class: 'btn btn-primary' %>
      </div>


    <%end%>

  </div>
</div>

app/views/payments/new.html.erb
<div class='mt-3'>
  <h3>سداد فاتورة : </h3>

  <div class='m-2'>
    <p><%= @payment.invoice.client.name %></p>
    <p>رقم الفاتورة : <%= @payment.invoice.number %></p>
    <p>قيمة الفاتورة : <%= @payment.invoice.value %></p>
    <p>المبلغ المتبقي : <%= @payment.invoice.payments_remaining %></p>
  </div>
  <div class='form-control'>

    <%= form_for @payment , url: payments_path do  |form| %>
      <% if @payment.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <% @payment.errors.full_messages.each do |msg| %>
            <div><%= '* ' + msg %></div>
          <% end %>
        </div>
      <% end %> 

      <%= form.hidden_field :invoice_id , value: @payment.invoice_id %>

      <div class='m-3'>
        <%= form.label "المبلغ", class: 'form-label' %>
        <%= form.text_field :amount, class: 'form-control' %>
      </div>

      <div class='m-3'>
        <%= form.label "طريقة السداد", class: 'form-label' %>
        <%= form.select :payment_method, [['نقدا','cash'], ['تحويل بنكي', 'transfer']], class: 'form-control' %>
      </div>

      <div class='m-3'>
        <%= form.label "تاريخ السداد", class: 'form-label' %>
        <%= form.date_field :date %>
      </div>

      <div class='m-3 mb-3'>
        <%= form.submit 'حفظ', class: 'btn btn-success' %>
        <%= link_to "عودة", client_path(@payment.invoice.client) , class: 'btn btn-primary' %>
      </div>


    <%end%>

  </div>
</div>